name: Build and Release apk

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17


      - name: Flutter action
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.0'

      - run: flutter pub get

      - run: flutter test

      - run: flutter build apk --release --target-platform=android-arm64
      
      - name: Release apk
        uses: actions/upload-artifact@main
        with:
          name: flutter_server_box
          path: "build/app/outputs/apk/release/*.apk"

