name: Build and Release apk

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  actions: write
env:
  PROPERTIES_PATH: './android/key.properties'

jobs:
  process:
    name: all process
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@main

      - name: Clone repo
        run: |
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          cd workdir
          git clone --depth 1 https://github.com/lollipopkit/flutter_server_box.git /apk


      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: 17


      - name: Set up Flutter
        uses: subosito/flutter-action@main
        with:
          channel: 'stable'

      - name: Set key
        working-directory: /workdir/apk
        run: |
          echo keyPassword=\${{ secrets.STOREPASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.STOREPASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEYALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=key.jks >> ${{env.PROPERTIES_PATH}}
          echo "${{ secrets.KEYSTORE2 }}" | base64 --decode > android/app/key.jks


      # Get Flutter dependencies.
      - name: Get Flutter dependencies
        working-directory: /workdir/apk
        run: flutter pub get

      # Check for any formatting issues in the code.
      - name: Check code formatting
        working-directory: /workdir/apk
        run: dart format --output=none .

      # Statically analyze the Dart code for any errors.
      - name: Analyze Dart code
        working-directory: /workdir/apk
        run: flutter analyze .

      - name: Build arm64 APK
        working-directory: /workdir/apk
        run: flutter build apk --release --target-platform=android-arm64
      
      - name: Release apk
        uses: actions/upload-artifact@main
        with:
          name: flutter_server_box
          path: "/workdir/apk/build/app/outputs/apk/release/*.apk"

      - name: Delete workflow runs
        uses: AoThen/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 5