name: Test, Build and Release apk

on:
  workflow_dispatch:

jobs:
  process:
    name: all process
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: "12.x"

      - name: Flutter action
        uses: subosito/flutter-action@v1.1.1
        with:
          channel: "stable"
          flutter-version: "1.12.x"

      - run: flutter pub get

      - run: flutter test

      - run: flutter build apk --release
      
      - name: Release apk
        uses: actions/upload-artifact@main
        with:
          name: flutter_server_box
          path: "build/app/outputs/apk/release/*.apk"

