name: Build and Release apk

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17


      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Get Flutter dependencies.
      - name: Get Flutter dependencies
        run: flutter pub get

      # Check for any formatting issues in the code.
      - name: Check code formatting
        run: dart format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - name: Analyze Dart code
        run: flutter analyze .

      - run: flutter build apk --release --split-per-abi --target-platform=android-arm64
      
      - name: Release apk
        uses: actions/upload-artifact@main
        with:
          name: flutter_server_box
          path: "build/app/outputs/apk/release/*.apk"

