name: Build and Release apk

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROPERTIES_PATH: './android/key.properties'

jobs:
  process:
    name: all process
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17


      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set key
        run: |
          echo keyPassword=\${{ secrets.STOREPASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.STOREPASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEYALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=key.jks >> ${{env.PROPERTIES_PATH}}
          echo "${{ secrets.KEYSTORE2 }}" | base64 --decode > android/app/key.jks


      # Get Flutter dependencies.
      - name: Get Flutter dependencies
        run: flutter pub get

      # Check for any formatting issues in the code.
      - name: Check code formatting
        run: dart format --output=none .

      # Statically analyze the Dart code for any errors.
      - name: Analyze Dart code
        run: flutter analyze .

      - name: Build arm64 APK
        run: flutter build apk --release --target-platform=android-arm64
      
      - name: Release apk
        uses: actions/upload-artifact@main
        with:
          name: flutter_server_box
          path: "build/app/outputs/apk/release/*.apk"

